#!/bin/bash
echo "=========================================="
echo "  环境诊断报告"
echo "=========================================="
echo ""
echo "1. 当前用户: $(whoami)"
echo "当前目录: $(pwd)"
echo "HOME: $HOME"
echo ""
echo "2. 环境变量检查:"
env | grep -E "ANDROID|HOME|USER" | sort
echo ""
echo "3. buildozer.spec 中的关键配置:"
grep -E "android\.ndk|android\.api|android\.sdk|p4a\." buildozer.spec | grep -v "^#"
echo ""
echo "4. 检查 buildozer.spec 中是否有硬编码路径:"
grep -n "asu_qin" buildozer.spec || echo "  未找到硬编码路径 ✅"
echo ""
echo "5. 检查 ~/.buildozer 目录:"
ls -la ~/.buildozer/ 2>/dev/null || echo "  ~/.buildozer 不存在"
echo ""
echo "6. 检查 NDK 相关:"
find ~/.buildozer -name "*ndk*" -type d 2>/dev/null | head -5 || echo "  未找到 NDK"
echo ""
echo "=========================================="
echo "  诊断完成"
echo "=========================================="
